#!/usr/bin/env bash

echo '<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>WebReflection Web Related Examples</title>
    <style>
    body {
      font-family: sans-serif;
    }
    ul, li {
      list-style: none;
      padding: 0;
      margin: 0;
    }
    a {
      display: block;
      padding: 16px;
    }
    a:hover {
      font-weight: bold;
    }
    </style>
  </head>
  <body>
    <ul>' > index.html

for d in $(ls); do
  if [ -d $d ]; then
    echo "      <li><a href='$d/'>$d</a></li>" >> index.html
  fi
done

echo '    </ul>
  </body>
</html>' >> index.html